# Generated by Django 2.2.4 on 2019-08-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataToAnalyze',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(verbose_name="L'utilisateur ayant uploadé ce fichier")),
                ('dataset', models.FileField(upload_to='data/', verbose_name='Fichier contenant les données')),
            ],
        ),
    ]
